// clientes/livros-next/pages/LivroLista.tsx
import type {NextPage} from 'next';
import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import { Menu } from '../componentes/Menu'; 
import styles from '../styles/Home.module.css'; 
import { LinhaLivro } from '../componentes/LinhaLivro'; 
import Livro from '../classes/modelo/Livro'; 

const baseURL = "http://localhost:3000/api/livros"; 

const obter = async () => {
    const response = await fetch(baseURL);
    return await response.json(); 
};

const excluirLivro = async (codigo: string | undefined) => {
    const response = await fetch(`${baseURL}/${codigo}`, {
        method: 'DELETE'
    });
    return response.ok; 
};

const LivroLista: React.FC = () => {
    const [livros, setLivros] = useState<Array<Livro>>([]); 
    const [carregado, setCarregado] = useState<boolean>(false); 

    useEffect(() => {
        obter()
            .then(data => {
                setLivros(data); 
                setCarregado(true); 
            })
            .catch(error => {
                console.error("Erro ao obter livros:", error);
            });
    }, []);

    const excluir = async (codigo: string | undefined) => {
        const sucesso = await excluirLivro(codigo);
        if (sucesso) {
            setLivros(livros.filter(livro => livro._id !== codigo)); 
            setCarregado(false); 
        }
    };

    return (
        <div className="container">
            <Head>
                <title>Lista de Livros</title>
            </Head>
            <Menu />
            <main className='col-9 mx-auto'>
                <h1 className={styles.h1}>Catálogo</h1>
                <table className="table table-striped">
                    <thead className='table-dark'>
                        <tr>
                            <th className="col-2">Título</th>
                            <th className="col-6">Resumo</th>
                            <th className="col-2">Editora</th>
                            <th className="col-2">Autores</th>
                        </tr>
                    </thead>
                    <tbody>
                        {livros.map(livro => (
                            <LinhaLivro
                                key={livro._id}
                                livro={livro}
                                excluir={() => excluir(livro._id)} 
                            />
                        ))}
                    </tbody>
                </table>
            </main>
        </div>
    );
}

export default LivroLista;

// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../editora';
import {Livro}  from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {

  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];
  private servEditora: ControleEditoraService;
  private servLivros: ControleLivrosService;

  constructor(servEditora: ControleEditoraService, servLivros: ControleLivrosService) {
    this.servEditora = servEditora;
    this.servLivros = servLivros;
  }

  // Método ngOnInit modificado para usar Promise e then
  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros()
      .then(livros => {
        this.livros = livros;  
      })
      .catch(erro => {
        console.error("Erro ao obter livros", erro);
      });
  }

  // Método excluir modificado para aceitar código como String
  excluir = (codigo: string): void => {
    console.log("Excluir livro com código:", codigo)
    this.servLivros.excluir(codigo)
      .then(() => {
        return this.servLivros.obterLivros();
      })
      .then(livros => {
        this.livros = livros;  
      })
      .catch(erro => {
        console.error("Erro ao excluir livro", erro);
      });
  };

  obterNome = (codEditora: number): string | undefined => {
    return this.servEditora.getNomeEditora(codEditora);
  };
}
<main class="container">
    <h1 class="mb-4">Catálogo de Livros</h1>

    <table class="table table-striped">
        <thead class="table-dark">
            <tr>
                <th class="col-2">Título</th>
                <th class="col-6">Resumo</th>
                <th class="col-2">Editora</th>
                <th class="col-2">Autores</th>
            </tr>
        </thead>
        <tbody>

            <tr *ngFor="let livro of livros">
                <td>
                    {{ livro.titulo }}
                    <div>
                        <button class="btn btn-danger" (click)="excluir(livro._id? livro._id : '')">
                            Excluir
                        </button>
                    </div>
                </td>
                <td>{{ livro.resumo}}</td>



                <td>{{ obterNome(livro.codEditora) }}</td>

                <td>
                    <ul>

                        <li *ngFor="let autor of livro.autores">{{ autor }}</li>
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>
</main>
