// clientes/livros-react/src/LivroDados.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import ControleLivros from './controle/ControleLivro';
import ControleEditora, {editoras} from './controle/ControleEditora';

const controleLivro = new ControleLivros();
const controleEditora = new ControleEditora(editoras);

const LivroDados = () => {
    const opcoes = controleEditora.getEditoras().map(editora => ({
        value: editora.codEditora,
        text: editora.nome
    }));

    const [titulo, setTitulo] = useState('');
    const [resumo, setResumo] = useState('');
    const [autores, setAutores] = useState([]);
    const [codEditora, setCodEditora] = useState(opcoes[0].value);

    const navigate = useNavigate();

    // Método tratarCombo para a combo de editoras
    const tratarCombo = (event) => {
        setCodEditora(Number(event.target.value));
    };

    // Método incluir
    const incluir = (event) => {
        event.preventDefault();

        const livro = {
            codigo: "", 
            titulo: titulo,
            resumo: resumo,
            autores: autores.split('\n'), 
            codEditora: codEditora
        };

        controleLivro.incluir(livro).then(() => {
            navigate('/');
        });
    };

    return (
        <main className='col-9 mx-auto'>
            <h1>Dados do Livro</h1>
            <form onSubmit={incluir}>
                <div className="mb-3">
                    <label className="form-label">Título</label>
                    <input type="text" className="form-control" value={titulo} onChange={(e) => setTitulo(e.target.value)} required />
                </div>

                <div className="mb-3">
                    <label className="form-label">Resumo</label>
                    <textarea className="form-control" value={resumo} onChange={(e) => setResumo(e.target.value)} required />
                </div>

                <div className="mb-3">
                    <label className="form-label">Autores (um por linha)</label>
                    <textarea className="form-control" value={autores} onChange={(e) => setAutores(e.target.value)} required />
                </div>

                <div className="mb-3">
                    <label className="form-label">Editora</label>
                    <select className="form-select" value={codEditora} onChange={tratarCombo}>
                        {opcoes.map((opcao) => (
                            <option key={opcao.value} value={opcao.value}>
                                {opcao.text}
                            </option>
                        ))}
                    </select>
                </div>

                <button type="submit" className="btn btn-primary">
                    Salvar Dados
                </button>
            </form>
        </main>
    );
};

export default LivroDados;

// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro = new Livro();       
  public autoresForm: string = '';         
  public editoras: Array<Editora> = [];    
  private servEditora: ControleEditoraService;
  private servLivros: ControleLivrosService;
  private router: Router;

  constructor(servEditora: ControleEditoraService, servLivros: ControleLivrosService, router: Router) {
    this.servEditora = servEditora;
    this.servLivros = servLivros;
    this.router = router;
  }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split('\n');
    
    this.servLivros.incluir(this.livro).then(() => {
      this.router.navigateByUrl('/lista');
    }).catch((erro) => {
      console.error('Erro ao incluir livro:', erro);
    });
  };
}
<main class="container mt-4">
    <h1 class="mb-4">Dados do Livro</h1>
    <form (submit)="incluir()" ngNativeValidate>

      <div class="mb-3">
        <label for="titulo" class="form-label">Título</label>
        <input
          type="text"
          id="titulo"
          class="form-control"
          [(ngModel)]="livro.titulo"
          name="titulo"
          required
        />
      </div>
  
      <div class="mb-3">
        <label for="resumo" class="form-label">Resumo</label>
        <textarea
          id="resumo"
          class="form-control"
          [(ngModel)]="livro.resumo"
          name="resumo"
        ></textarea>
      </div>
  
      <div class="mb-3">
        <label for="editora" class="form-label">Editora</label>
        <select
          id="editora"
          class="form-select"
          [(ngModel)]="livro.codEditora"
          name="editora"
          required
        >
          <option *ngFor="let editora of editoras" [value]="editora.codEditora">
            {{ editora.nome }}
          </option>
        </select>
      </div>
  
      <div class="mb-3">
        <label for="autores" class="form-label">Autores (1 por linha)</label>
        <textarea
          id="autores"
          class="form-control"
          [(ngModel)]="autoresForm"
          name="autores"
        ></textarea>
      </div>
  
      <button type="submit" class="btn btn-primary">Salvar Dados</button>
    </form>
  </main>
